image:
  - Visual Studio 2017
clone_folder: c:\projects\source
environment:
  
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_64_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib64-msvc-14.1
build_script:
- cmd: >-
    if not exist build
    mkdir build

    cd build

    cmake c:\projects\source -G "Visual Studio 15 2017 Win64"

    cmake --build . --config "Debug"

    cmake --build . --config "Release"

test_script:
- cmd: >-
    ctest -C "Debug"
